name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ci:
    uses: 0x-wzw/ci-cd-templates/.github/workflows/node-standard.yml@main
    with:
      node-version: '20'
      package-manager: 'npm'
      has-docker: false
    secrets:
      inherit

